### ISSUE TITLE
Covariates and zero observations

### ISSUE THREAD

**Issue by ghost** [ericward-noaa/bycatch#1]
Hi Eric -
  Working with this package, I noticed two separate issues.
  1. I cannot seem to get the covariates to work.
  2. When there are zero observations for the entire time series, I get very large estimates of bycatch.  I expect some bycatch even when observers never observed bycatch, but not in the range of 100's per year.
  
  Let me know if you'd like me to supply some example data sets.

  Cheers
  Jason

**Comment by ericward-noaa** [comment]
For the covariates, I included an example in the vignette folder here (but let me know if it's not working on your data for some reason)

https://github.com/eric-ward/bycatch/tree/master/vignettes

**Comment by ericward-noaa** [comment]
And for the zero-take example, I included a demo of that at the bottom of the vignette too. I get it to run ok, but there's some warnings about lack of convergence. If yours isn't running, maybe send me an example and I'll see where the problem is.

**Comment by ghost** [comment]
I will work on an MWE.
